### PR TITLE
minor doc text updates

### PR DESCRIPTION
**Pull request by WestleyArgentum**
- fixed the name of the "frames.yaml" example file
- added a doc with simple instructions for configuring yolov for the first time
- added the example command for "yolov3.yaml" just to make it easy

### CODE REVIEW

**Comment by breezykermo** [comment]
Thanks so much for this- it's resolving similar changes proposed in #116, see comments there for status.

**Comment by breezykermo** [comment]
@WestleyArgentum would you be able to confirm that #117 makes this extra yolov3 setup unnecessary? If so, let's change this just to the typo fix for frames.yaml, and then I can merge.

**Comment by breezykermo** [comment]
@WestleyArgentum can I close this?

**Comment by WestleyArgentum** [comment]
Yep, the other PR addressed this, closing!

**Pull request closed without merging**
