### PR TITLE
Issue/viewer etypes 76

### LINKED ISSUE #76: use etypes in viewer
the viewer server should cast element contents to etypes before creating symlinks that make media available as resources across the network. (This will require a cast_to_etype implementation in Go, which is no biggie.) Perhaps we can rethink how element media is structured when it is served to viewers via etypes, too.

### PR DESCRIPTION
**Pull request by samludford**
closes #76 

Server casts elements to expected etype provided by the viewer plugin in a required `config.json`.

### CODE REVIEW

**Comment by samludford** [comment]
Due to language differences Etype & casting implementations were quite different in Go from the python version.  It would probably be a good idea to define etypes in a json/yaml file which is read by both Go and python implementations, otherwise things could become fragile quickly.

**Comment by breezykermo** [comment]
> Due to language differences Etype & casting implementations were quite different in Go from the python version. It would probably be a good idea to define etypes in a json/yaml file which is read by both Go and python implementations, otherwise things could become fragile quickly.

This is a great idea. It would also remove a lot of the redundancy/hardcode in both Go and Python implementations.

**Comment by breezykermo** [comment]
It's hard to know whether this works without:
1. Tests for the outer run.py code. (You can add these to the outer test/ folder.)
2. At least one example viewer in src/lib. 

@samludford could you add a basic example viewer and tests?

**Review by breezykermo — CHANGES_REQUESTED** [review]
Another thing we perhaps want to think about is a testing infrastructure for the Golang code. Go has [testing utils](https://golang.org/pkg/testing/)-- and perhaps this is a good opportunity to think on some more focused unit tests for etypes. (When we wrote tests in #75, they were more integration-ey across selector/analyser workflows, it felt.)

**Comment by samludford** [comment]
Added an example viewer plugin, and tests for run.py's viewer plugin orchestration.

**Comment by breezykermo** [comment]
Some notes for a future PR:
* The `view` command doesn't need to build from scratch each time, it can actually just pull viewer Dockerfiles from Dockerhub. Then there should be a tag to pass that builds locally instead (which is run with the CI when a viewer is updated).

**Review by breezykermo — APPROVED** [review]

**Pull request merged**
