### PR TITLE
4chan selector

### PR DESCRIPTION
**Pull request by jamesb93**
This selector allows you to grab the contents from a 4chan 'board' at any given time. The selector scrapes every post, for every thread in each page of a board up to a given page limit. It places the comment of each post and any associated media into a folder at the destination.

The only configuration parameters that it takes are a board name, so 'g' for technology board for example and a maximum amount of pages to scrape as an integer. I thought about implementing the ability to add a search query so that only posts containing certain text information are returned. Seeing as 4chan allows posts to contain only media and no comments it doesn't make sense to query at the ./mtriage stage but after with all of the data that is scraped.

I'd appreciate hearing any thoughts on implementation and interface that you have or suggestions for adding useful functionality.

### CODE REVIEW

**Comment by breezykermo** [comment]
Sorry for the major delay on merging this PR. The reason for it is that I'm in the middle of a major rewrite of mtriage internals, which will affect the way that all selectors and analysers are composed, as it modifies the component API.

After it's complete, I'll review this branch (which will probably require a few minor changes due to the rewrite), and look to merge it. :)

**Comment by jamesb93** [comment]
> Sorry for the major delay on merging this PR. The reason for it is that I'm in the middle of a major rewrite of mtriage internals, which will affect the way that all selectors and analysers are composed, as it modifies the component API.
> 
> After it's complete, I'll review this branch (which will probably require a few minor changes due to the rewrite), and look to merge it. :)

Great! Looking forward to seeing it on master ;)

**Comment by breezykermo** [comment]
@jamesb93, would you be interested in porting this to the new component API? Let me know if anything about the new structure isn't clear.

**Comment by jamesb93** [comment]
> @jamesb93, would you be interested in porting this to the new component API? Let me know if anything about the new structure isn't clear.

Yep, i'd be happy to update this PR with the new api.

**Comment by breezykermo** [comment]
Hey @jamesb93 how is this going? I've picked up the slack on other things, and ready to review this whenever. If you can rebase onto release once you've made the refactor that'd be great!

**Comment by jamesb93** [comment]
yep I made some initial headway but got stuck fighting docker. I'll have to have to go back in but things have been busy with corona related hitches everywhere else in life. Shouldn't be too long!

**Comment by breezykermo** [comment]
Hey @jamesb93, I [opened a PR](https://github.com/jamesb93/mtriage/pull/1) on your repo with some suggestions, as this is what seems easiest to me in terms of making suggestions. Let me know if you have any questions, this is pretty close to being merged!

**Comment by jamesb93** [comment]
Sorry for the long wait, I think this is done now! Let me know if you catch anything that needs changing.

**Comment by breezykermo** [comment]
@jamesb93 my turn to apologize: mtriage dev has really taken a back seat recently.

I think that there are still a few things to sort out in this component, i.e. limiting the way that the selector indexes the boards-- but I've just merged so that we can move forward, and I'll work on fixing in follow up PRs. Thanks again for this contribution!

**Pull request merged**
