### PR TITLE
Typing

### PR DESCRIPTION
**Pull request by jamesb93**
I've made this pull request perhaps prematurely but I think that the typing is very close to completion on all of the code that is common across mtriage. There are a couple of corners where I haven't been able to figure out what the appropriate type is.

1. https://github.com/forensic-architecture/mtriage/blob/416fae10130fe6e98a90ab58edccb437fc3816e4/src/lib/common/get_module.py#L5

2. https://github.com/forensic-architecture/mtriage/blob/416fae10130fe6e98a90ab58edccb437fc3816e4/src/lib/common/selector.py#L23

So far I have tested it on the twitter selector without any errors.

### CODE REVIEW

**Comment by breezykermo** [comment]
Similarly on this PR, [could you cherrypick commits](https://github.com/forensic-architecture/mtriage/pull/137#issuecomment-586663106)? It should also fix the conflicts that are currently showing.

**Comment by jamesb93** [comment]
The errors I'm getting from travis are a bit arcane to me. When you get some time, would you be able to point me towards the error?

**Comment by breezykermo** [comment]
Sorry for the delay on this: see [my comment here](https://github.com/forensic-architecture/mtriage/pull/139#issuecomment-596170567).

The rewrite will close this issue I think, as I've typed most of the internals in it.

**Comment by breezykermo** [comment]
The new component API has done a lot of the internal typing here, and changed many of the types. I'll close this if it makes sense to you

**Comment by jamesb93** [comment]
> The new component API has done a lot of the internal typing here, and changed many of the types. I'll close this if it makes sense to you

Yep, this makes sense.

**Pull request closed without merging**
