### PR TITLE
Add 4chan selector

### PR DESCRIPTION
**Pull request by jamesb93**
This selector allows you to grab the contents from a 4chan 'board' at any given time. The selector scrapes every post, for every thread in each page of a board up to a given page limit. It places the comment of each post and any associated media into a folder at the destination. 

The only configuration parameters that it takes are a board name, so 'g' for technology board for example and a maximum amount of pages to scrape as an integer. I thought about implementing the ability to add a search query so that only posts containing certain text information are returned. Seeing as 4chan allows posts to contain only media and no comments it doesn't make sense to query at the `./mtriage` stage but after with all of the data that is scraped.

I'd appreciate hearing any thoughts on implementation and interface that you have or suggestions for adding useful functionality.

### CODE REVIEW

**Comment by breezykermo** [comment]
Heya, thanks for the PR! The build is currently failing because the files are not formatted with [black](https://github.com/psf/black) (another thing that needs to be documented for developers...). There a script in the 'scripts' folder you can run, so long as black is installed on your local: `sh scripts/lint.sh`.

**Comment by jamesb93** [comment]
> Heya, thanks for the PR! The build is currently failing because the files are not formatted with [black](https://github.com/psf/black) (another thing that needs to be documented for developers...). There a script in the 'scripts' folder you can run, so long as black is installed on your local: `sh scripts/lint.sh`.

Done! Let's see how that one goes past the checks.

**Comment by breezykermo** [comment]
One more logistical thing before I review sorry: could you rebase or cherry pick your commits on top of the latest release? A few additions in docs and edits in the keras_pretrained.yml are showing up for me on this branch currently.

The 'whitelist.txt' file should also be removed from git. If you put it in a 'whitelists' folder it [will be gitignored](https://github.com/forensic-architecture/mtriage/blob/master/.gitignore#L29).

**Comment by jamesb93** [comment]
> One more logistical thing before I review sorry: could you rebase or cherry pick your commits on top of the latest release? A few additions in docs and edits in the keras_pretrained.yml are showing up for me on this branch currently.
> 
> The 'whitelist.txt' file should also be removed from git. If you put it in a 'whitelists' folder it [will be gitignored](https://github.com/forensic-architecture/mtriage/blob/master/.gitignore#L29).

Ah, I was working off the master branch not release. Let me clean that up now.

**Comment by jamesb93** [comment]
I'm actually going to close this and add a new PR from the rebase. I think it will be much cleaner as I won't be trying to merge from a master branch, but from a feature branch called 4chan-selector. Sorry if this makes things messier in the repo overall by adding new PR's.

**Pull request closed without merging**
